name: Test

on:
  workflow_dispatch:
    inputs:
      "--- ⚠️ INSTRUCTION ⚠️ ---":
        description: "Please select the right tag before launch the workflow."
        required: false
      # This input is defined to false for a release. -> Apply the canary deployment
      # When we want to rollback etc ... we need to set this value to true to disable the canary deployment
      skip-progressive-rollout:
        type: boolean
        description: |
          Uncheck - Do a progressive rollout
          Check - Do an instant deployment
        default: false

jobs:
  test:
    name: Test
    steps:
      - name: Test
        run: echo "This is a test step"